title: Storch
description: "Redcup: An awesome Theme for Jekyll"

url: https://stoerchl.github.io/
port: 3000
highlighter: rouge

permalink: /:year/:month/:day/:title.html
markdown: kramdown

google_analytics: #

owner:
  name: Storch
  disqus_shortname: stoerchl-github-io
  twitter: stoerchl
